apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: bot
  name: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bot
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: bot
    spec:
      containers:
        - image: lucawen/sheepbot
          name: bot
          resources: {}
          env:
          - name: DATABASE_URL
            value: ${SECRET_SHEEPBOT_DATABASE_URL}
          - name: BOT_DISCORD_PREFIX
            value: ${SECRET_SHEEPBOT_DISCORD_PREFIX}
          - name: BOT_DISCORD_TOKEN
            value: ${SECRET_SHEEPBOT_DISCORD_TOKEN}
          - name: BOT_LAVALINK_URL
            value: ${SECRET_SHEEPBOT_LAVALINK_URL}
          - name: BOT_LAVALINK_PASSWORD
            value: ${SECRET_SHEEPBOT_LAVALINK_PASSWORD}
      restartPolicy: Always
status: {}
