apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: bot
  name: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bot
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: bot
    spec:
      containers:
        - image: lucawen/sheepbot
          name: bot
          resources: {}
          env:
          - name: BOT_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: sheepbot-creds
                key: DATABASE_URL
          - name: BOT_DISCORD__PREFIX
            valueFrom:
              secretKeyRef:
                name: sheepbot-creds
                key: DISCORD_PREFIX
          - name: BOT_DISCORD__TOKEN
            valueFrom:
              secretKeyRef:
                name: sheepbot-creds
                key: DISCORD_TOKEN
          - name: BOT_LAVALINK__URL
            valueFrom:
              secretKeyRef:
                name: sheepbot-creds
                key: LAVALINK_URL
          - name: BOT_LAVALINK__PASSWORD
            valueFrom:
              secretKeyRef:
                name: sheepbot-creds
                key: LAVALINK_PASSWORD
          - name: BOT_SPOTIFY__CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: sheepbot-creds
                key: SPOTIFY_CLIENT_ID
          - name: BOT_SPOTIFY__CLIENT_TOKEN
            valueFrom:
              secretKeyRef:
                name: sheepbot-creds
                key: SPOTIFY_CLIENT_TOKEN
      restartPolicy: Always
status: {}
