apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: bot
  name: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bot
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: bot
    spec:
      containers:
        - image: lucawen/sheepbot
          name: bot
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: sheepbot-creds
                key: DATABASE_URL
          - name: BOT_DISCORD_PREFIX
            valueFrom:
              secretKeyRef:
                name: sheepbot-creds
                key: DISCORD_PREFIX
          - name: BOT_DISCORD_TOKEN
            valueFrom:
              secretKeyRef:
                name: sheepbot-creds
                key: DISCORD_TOKEN
          - name: BOT_LAVALINK_URL
            valueFrom:
              secretKeyRef:
                name: sheepbot-creds
                key: LAVALINK_URL
          - name: BOT_LAVALINK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sheepbot-creds
                key: LAVALINK_PASSWORD

        - name: db
          image: postgres:12
          imagePullPolicy: "IfNotPresent"
          env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: sheepbot-creds
                key: DATABASE_DB
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sheepbot-creds
                key: DATABASE_PASSWORD
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

        - image: fredboat/lavalink:master
          name: lavalink
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "500m"
              cpu: "1G"
          volumeMounts:
            - mountPath: /opt/Lavalink/application.yml
              name: lavalink-claim0
      volumes:
        - name: lavalink-claim0
          persistentVolumeClaim:
            claimName: lavalink-claim0
      restartPolicy: Always
status: {}
