apiVersion: v1
kind: Service
metadata:
  name: sheepbot-lavalink
  labels:
    io.kompose.service: sheepbot-lavalink
spec:
  ports:
  - port: 2333
    protocol: TCP
  selector:
    io.kompose.service: sheepbot-lavalink