apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: lavalink
  name: lavalink
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lavalink
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: lavalink
    spec:
      containers:
        - image: fredboat/lavalink:master
          name: lavalink
          resources: {}
          volumeMounts:
            - mountPath: /opt/Lavalink/application.yml
              name: lavalink-cm1
              subPath: application.yml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: application.yml
                path: application.yml
            name: lavalink-cm1
          name: lavalink-cm1
status: {}
