---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 10.0.0.210-10.0.0.250
  INGRESS_NGINX_LB: 10.0.0.220
  SVC_TRAEFIK_ADDRESS: 10.0.0.220
