---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      version: 10.1.2
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
      interval: 5m
  values:
    deployment:
      enabled: true
      kind: DaemonSet
      # replicas: 3
    service:
      enabled: true
      type: LoadBalancer
      spec:
        externalIPs:
          - "${SVC_TRAEFIK_ADDRESS}"
        externalTrafficPolicy: Local
    logs:
      general:
        format: json
        level: DEBUG
      access:
        enabled: true
        format: json
    ingressClass:
      enabled: true
      isDefaultClass: true
      fallbackApiVersion: v1
    ingressRoute:
      dashboard:
        enabled: false
    globalArguments:
      - "--serverstransport.insecureskipverify=true"
      - "--providers.kubernetesingress.ingressclass=traefik"
      # - "--metrics.prometheus=true"
      # - "--metrics.prometheus.entryPoint=metrics"
    additionalArguments:
      - "--providers.kubernetesingress.ingressendpoint.ip=${SVC_TRAEFIK_ADDRESS}"
    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
          options: "default"
      metrics:
        port: 8082
        expose: true
        exposedPort: 8082
    tlsOptions:
      default:
        minVersion: VersionTLS12
        maxVersion: VersionTLS13
        sniStrict: true
    pilot:
      enabled: false
    experimental:
      plugins:
        enabled: true
    nodeSelector:
      node-role.kubernetes.io/master: "true"
    # affinity:
    #   podAntiAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #     - labelSelector:
    #         matchExpressions:
    #         - key: app.kubernetes.io/name
    #           operator: In
    #           values:
    #           - traefik
    #       topologyKey: kubernetes.io/hostname
    resources:
      requests:
        memory: 100Mi
        cpu: 500m
      limits:
        memory: 500Mi