---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: rfc1918-ips
  namespace: networking
spec:
  ipWhiteList:
    sourceRange:
      - 10.0.0.0/8
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: rfc1918
  namespace: networking
spec:
  chain:
    middlewares:
      - name: rfc1918-ips