---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-auth
  namespace: network
spec:
  chain:
    middlewares:
      - name: security-ak-outpost-traefik@kubernetescrd